### PR TITLE
Fix build on Archlinux due to libgvplugin_dot_layout.so not being found

### PR DESCRIPTION
**Pull request by iamsergio**
On Archlinux, it's in /usr/lib/graphviz/ not /usr/lib

Adapted FindGraphviz.cmake to find the full location and use it if found.

### CODE REVIEW

**Comment by dantti** [comment]
not sure it was already broken, but your last commit seems to have broken ci

**Comment by dantti** [comment]
BTW since graphviz has broke a lot in the past the idea was to not support distro versions, also macOS/Windows precompiled versions had issues.
But not against this, just that we should worry if regression/bugs whatever happens...

**Comment by iamsergio** [comment]
> BTW since graphviz has broke a lot in the past the idea was to not support distro versions, also macOS/Windows precompiled versions had issues. But not against this, just that we should not worry if regression/bugs whatever happens...

was unrelatead, CI is now fixed

**Comment by iamsergio** [comment]
> BTW since graphviz has broke a lot in the past the idea was to not support distro versions, also macOS/Windows precompiled versions had issues. But not against this, just that we should not worry if regression/bugs whatever happens...

agreed

**Comment by iamsergio** [comment]
> BTW since graphviz has broke a lot in the past the idea was to not support distro versions, also macOS/Windows precompiled versions had issues. But not against this, just that we should not worry if regression/bugs whatever happens...

Reopening since I'm not against it either and the patch works.

Turns out getting it to work on Homebrew with internal graphviz was more difficult since it misses lots of external dependencies (which probably are already installed in GH CI so it works there).

With this patch it builds and brew brings in the correct dependencies automatically.

**Pull request merged**
