### PR TITLE
Fix non-standand installation dirs

### PR DESCRIPTION
**Pull request by Petross404**
As stated in [here](https://github.com/KDAB/KDStateMachineEditor/issues/11), Gentoo doesn't accept not standard installation dirs. If you would be so kind to accept this, I would be able to make an ebuild for KDStateMachineEditor and (later) Gammaray :)

### CODE REVIEW

**Comment by Petross404** [comment]
One thing though : FULL variables aren't needed. ${CMAKE_INSTALL_BINDIR} would suffice.

**Comment by winterz** [comment]
looks good to me.
@krf please review and commit (or not) soon .  I want to release this as part of KDSME 1.2.2 very soon.

**Comment by krf** [comment]
@winterz Thanks. Merged!

**Comment by krf** [comment]
@Petross404 Just for future pull requests: Please make sure you've set a proper real name in Git; it's currently set to "Petross404".

https://help.github.com/articles/setting-your-username-in-git/

**Comment by Petross404** [comment]
Thanks! Already changed it.

**Pull request closed without merging**
